'use strict';

/**
 * models/predictionRecordModel.js
 *
 * Stores each AI risk prediction event, keyed to the triggering action.
 * triggered_by = "pdf_import" for records generated by importHealthPdf.
 */

const mongoose = require('mongoose');

const predictionRecordSchema = new mongoose.Schema(
    {
        user_id: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
            index: true,
        },
        risk_score: {
            type: Number,
            min: 0,
            max: 1,
            required: true,
        },
        risk_level: {
            type: String,
            enum: ['low', 'moderate', 'high'],
            required: true,
        },
        triggered_by: {
            type: String,
            default: 'pdf_import',
        },
        features_snapshot: {
            // Store the feature vector used so predictions are auditable
            avg_hr: { type: Number, default: null },
            max_hr: { type: Number, default: null },
            min_hr: { type: Number, default: null },
            exercise_sessions: { type: Number, default: null },
            resting_hr_trend: { type: Number, default: null },
        },
    },
    {
        timestamps: true,   // createdAt acts as prediction timestamp
        versionKey: false,
    }
);

// Fetch latest prediction per user efficiently
predictionRecordSchema.index({ user_id: 1, createdAt: -1 });

module.exports = mongoose.model('PredictionRecord', predictionRecordSchema);
