import { useState, useEffect, useCallback } from 'react';
import { Search, Trash2, FileText, ChevronLeft, ChevronRight, Eye, Calendar, User, TrendingUp } from 'lucide-react';
import { getAllReports, deleteReport } from '../../services/reportService';
import { useToast } from '../../components/ui/Toast';
import Spinner from '../../components/ui/Spinner';

export default function AdminReports() {
    const { toast } = useToast();

    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');
    const [page, setPage] = useState(1);
    const [pagination, setPagination] = useState({ totalPages: 1, total: 0 });
    const [selectedReport, setSelectedReport] = useState(null);

    const fetchReports = useCallback(async () => {
        try {
            setLoading(true);
            const res = await getAllReports(page, 10, search);
            setReports(res.data.data);
            setPagination(res.data.meta);
        } catch (err) {
            console.error('Fetch error:', err);
            toast.error('Failed to fetch reports.');
        } finally {
            setLoading(false);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [search, page]);

    useEffect(() => { fetchReports(); }, [fetchReports]);

    // Reset to page 1 on search
    useEffect(() => { setPage(1); }, [search]);

    const handleDelete = async (report) => {
        if (!confirm(`Are you sure you want to delete this report for ${report.user.fullName}?`)) return;
        try {
            await deleteReport(report._id);
            toast.success('Report deleted successfully.');
            fetchReports();
        } catch (err) {
            toast.error('Failed to delete report.');
        }
    };

    const getRiskColor = (level) => {
        const colors = {
            high: 'bg-red-100 text-red-700 ring-red-200',
            moderate: 'bg-orange-100 text-orange-700 ring-orange-200',
            low: 'bg-green-100 text-green-700 ring-green-200',
        };
        return colors[level] || 'bg-gray-100 text-gray-700 ring-gray-200';
    };

    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            {/* Header */}
            <div className="mb-8">
                <div className="flex items-center gap-3 mb-2">
                    <div className="p-2 bg-blue-100 rounded-xl">
                        <FileText className="w-6 h-6 text-blue-600" />
                    </div>
                    <h1 className="text-2xl font-bold text-gray-900">Report Management</h1>
                </div>
                <p className="text-sm text-gray-500">
                    Oversee and moderate all health reports generated by the AI engine — {pagination.total} total
                </p>
            </div>

            {/* Filters */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 mb-6 sticky top-4 z-20 backdrop-blur-md bg-white/80">
                <div className="relative max-w-md">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                    <input 
                        value={search} 
                        onChange={e => setSearch(e.target.value)}
                        placeholder="Search by user name or email..."
                        className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all" 
                    />
                </div>
            </div>

            {/* Table */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden min-h-[400px]">
                {loading ? (
                    <div className="flex flex-col items-center justify-center py-24">
                        <Spinner size="lg" />
                        <p className="mt-4 text-sm text-gray-500 animate-pulse">Loading reports...</p>
                    </div>
                ) : reports.length === 0 ? (
                    <div className="text-center py-24 text-gray-400">
                        <div className="w-20 h-20 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-4 border border-dashed border-gray-200">
                            <Search className="w-8 h-8 opacity-20" />
                        </div>
                        <p className="font-semibold text-gray-600">No reports matched your search</p>
                        <p className="text-sm mt-1">Try a different name or email address</p>
                    </div>
                ) : (
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                            <thead className="bg-gray-50/80 border-b border-gray-100">
                                <tr>
                                    {['User', 'Type', 'Period', 'Risk Level', 'Score', 'Actions'].map(h => (
                                        <th key={h} className="text-left px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-widest">{h}</th>
                                    ))}
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-50">
                                {reports.map(r => {
                                    const u = r.user || {};
                                    const initials = u.fullName?.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase();
                                    return (
                                        <tr key={r._id} className="hover:bg-blue-50/30 transition group">
                                            {/* User */}
                                            <td className="px-6 py-4">
                                                <div className="flex items-center gap-3">
                                                    {u.profileImage
                                                        ? <img src={`http://localhost:5001${u.profileImage}`} alt="" className="h-9 w-9 rounded-full object-cover ring-2 ring-white shadow-sm" />
                                                        : <div className="h-9 w-9 rounded-full bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-white text-xs font-bold shadow-sm">{initials}</div>
                                                    }
                                                    <div>
                                                        <p className="font-bold text-gray-900 group-hover:text-blue-700 transition-colors uppercase tracking-tight text-[13px]">{u.fullName}</p>
                                                        <p className="text-[11px] text-gray-400 font-medium">{u.email}</p>
                                                    </div>
                                                </div>
                                            </td>
                                            {/* Type */}
                                            <td className="px-6 py-4">
                                                <span className={`px-2.5 py-1 rounded-lg text-[10px] font-bold uppercase tracking-wider ${r.report_type === 'weekly' ? 'bg-indigo-50 text-indigo-600' : r.report_type === 'monthly' ? 'bg-purple-50 text-purple-600' : 'bg-emerald-50 text-emerald-600'}`}>
                                                    {r.report_type || 'custom'}
                                                </span>
                                            </td>
                                            {/* Period */}
                                            <td className="px-6 py-4 text-gray-600 text-[11px]">
                                                <div className="flex items-center gap-1.5">
                                                    <Calendar className="w-3 h-3 text-gray-300" />
                                                    <span>{new Date(r.start_date).toLocaleDateString()} - {new Date(r.end_date).toLocaleDateString()}</span>
                                                </div>
                                            </td>
                                            {/* Risk Level */}
                                            <td className="px-6 py-4">
                                                <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[11px] font-bold uppercase tracking-wide ring-1 ring-inset ${getRiskColor(r.predicted_risk_level)}`}>
                                                    <span className={`h-1.5 w-1.5 rounded-full ${r.predicted_risk_level === 'high' ? 'bg-red-500' : r.predicted_risk_level === 'moderate' ? 'bg-orange-500' : 'bg-green-500'}`} />
                                                    {r.predicted_risk_level}
                                                </span>
                                            </td>
                                            {/* Score */}
                                            <td className="px-6 py-4 font-mono text-gray-500 text-xs">
                                                {(r.predicted_risk_score * 100).toFixed(1)}%
                                            </td>
                                            {/* Actions */}
                                            <td className="px-6 py-4">
                                                <div className="flex items-center gap-2">
                                                    <button 
                                                        onClick={() => setSelectedReport(r)} 
                                                        title="View Details"
                                                        className="p-2 rounded-xl text-gray-400 hover:bg-white hover:text-blue-600 hover:shadow-sm border border-transparent hover:border-blue-100 transition-all"
                                                    >
                                                        <Eye className="w-4 h-4" />
                                                    </button>
                                                    <button 
                                                        onClick={() => handleDelete(r)} 
                                                        title="Delete Report"
                                                        className="p-2 rounded-xl text-gray-400 hover:bg-red-50 hover:text-red-600 border border-transparent hover:border-red-100 transition-all"
                                                    >
                                                        <Trash2 className="w-4 h-4" />
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                )}

                {/* Pagination */}
                {pagination.totalPages > 1 && (
                    <div className="flex items-center justify-between px-6 py-4 bg-gray-50/50 border-t border-gray-100">
                        <p className="text-xs font-medium text-gray-500 italic">Showing page {page} of {pagination.totalPages}</p>
                        <div className="flex gap-2">
                            <button 
                                disabled={page <= 1} 
                                onClick={() => setPage(p => p - 1)}
                                className="p-2 rounded-xl bg-white border border-gray-200 disabled:opacity-40 hover:bg-gray-50 hover:border-gray-300 transition shadow-sm"
                            >
                                <ChevronLeft className="w-4 h-4" />
                            </button>
                            <button 
                                disabled={page >= pagination.totalPages} 
                                onClick={() => setPage(p => p + 1)}
                                className="p-2 rounded-xl bg-white border border-gray-200 disabled:opacity-40 hover:bg-gray-50 hover:border-gray-300 transition shadow-sm"
                            >
                                <ChevronRight className="w-4 h-4" />
                            </button>
                        </div>
                    </div>
                )}
            </div>

            {/* Report Detail Modal */}
            {selectedReport && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/60 backdrop-blur-md p-4 animate-in fade-in duration-300"
                    onClick={() => setSelectedReport(null)}>
                    <div className="bg-white rounded-3xl shadow-2xl overflow-hidden w-full max-w-lg animate-in zoom-in duration-300" 
                        onClick={e => e.stopPropagation()}>
                        {/* Modal Header */}
                        <div className="bg-gradient-to-r from-blue-600 to-indigo-700 px-6 py-6 text-white relative">
                            <div className="flex items-center gap-4">
                                <div className="h-16 w-16 rounded-2xl bg-white/20 backdrop-blur-sm border border-white/30 flex items-center justify-center text-2xl font-black shadow-inner">
                                    {selectedReport.user.fullName?.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase()}
                                </div>
                                <div>
                                    <h2 className="text-xl font-black tracking-tight uppercase">{selectedReport.user.fullName}</h2>
                                    <p className="text-blue-100 text-xs font-medium opacity-80">{selectedReport.user.email}</p>
                                </div>
                            </div>
                            <div className="absolute top-6 right-6 px-3 py-1 bg-white/10 rounded-lg text-[10px] font-black uppercase tracking-widest border border-white/20">
                                {selectedReport.report_type} REPORT
                            </div>
                        </div>

                        {/* Modal Content */}
                        <div className="p-8 space-y-6">
                            <div className="grid grid-cols-2 gap-4">
                                <div className="p-4 bg-gray-50 rounded-2xl border border-gray-100">
                                    <p className="text-[10px] uppercase font-black text-gray-400 tracking-widest mb-1">Risk Score</p>
                                    <div className="flex items-baseline gap-1">
                                        <span className="text-2xl font-black text-gray-900">{(selectedReport.predicted_risk_score * 100).toFixed(1)}</span>
                                        <span className="text-sm font-bold text-gray-400">%</span>
                                    </div>
                                </div>
                                <div className={`p-4 rounded-2xl border ring-4 ring-inset ${
                                    selectedReport.predicted_risk_level === 'high' ? 'bg-red-50 border-red-100 ring-red-500/5' : 
                                    selectedReport.predicted_risk_level === 'moderate' ? 'bg-orange-50 border-orange-100 ring-orange-500/5' : 
                                    'bg-green-50 border-green-100 ring-green-500/5'
                                }`}>
                                    <p className="text-[10px] uppercase font-black opacity-50 tracking-widest mb-1">Risk Level</p>
                                    <p className={`text-xl font-black uppercase tracking-tight ${
                                        selectedReport.predicted_risk_level === 'high' ? 'text-red-700' : 
                                        selectedReport.predicted_risk_level === 'moderate' ? 'text-orange-700' : 
                                        'text-green-700'
                                    }`}>{selectedReport.predicted_risk_level}</p>
                                </div>
                            </div>

                            <div className="space-y-3">
                                <h3 className="text-xs font-black text-gray-400 uppercase tracking-widest flex items-center gap-2">
                                    <TrendingUp className="w-3 h-3" />
                                    Metric Highlights
                                </h3>
                                <div className="grid grid-cols-2 gap-x-8 gap-y-3 text-sm">
                                    {[
                                        ['Sleep', `${selectedReport.avg_sleep_duration || 0} hrs`],
                                        ['Stress', `${selectedReport.avg_stress_level || 0}/10`],
                                        ['Heart Rate', `${selectedReport.avg_heart_rate || 0} bpm`],
                                        ['BMI', (selectedReport.avg_bmi || 0).toFixed(1)],
                                        ['Steps', `${selectedReport.avg_steps || 0} /day`],
                                        ['Calories', `${selectedReport.avg_calories || 0} kcal`],
                                    ].map(([label, val]) => (
                                        <div key={label} className="flex justify-between items-center py-2 border-b border-gray-50 group hover:border-blue-100 transition-colors">
                                            <span className="text-gray-500 font-bold text-xs">{label}</span>
                                            <span className="text-gray-900 font-black tracking-tight">{val}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            <button onClick={() => setSelectedReport(null)}
                                className="w-full py-4 bg-gray-900 hover:bg-black text-white rounded-2xl text-xs font-black uppercase tracking-widest transition-all shadow-xl shadow-gray-200">
                                Close Details
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
